apiVersion: v1
kind: Service
metadata:
  name: insta-js
  labels:
    app: insta-js
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: insta-js
